# metadata
apiVersion: apps/v1
# Deployment | Service
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    apps: nginx-dep

# specification
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers: 
        - name: nginx
          image: nginx:1.16
          ports:
          - containerPort: 8888