apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-depl
  labels:
    apps: mongodb
 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec: 
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
        env: 
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
  # link to mongo deployment selector above
    app: mongodb
  # type: LoadBalancer
  ports:
    - protocol: TCP
      # service port
      port: 27017
      # containerPort of deployment
      targetPort: 27017
      # external port
      # nodePort: 30000