apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-username: bW9uZ29hZG1pbg==
  mongo-password: bW9uZ29hZG1pbg==
  mongo-express-username: aGFudA==
  mongo-express-password: aGFudA==
