apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    apps: mongo-express

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec: 
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
        - name: express-port
          containerPort: 4444
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
        - name: ME_CONFIG_BASICAUTH_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-express-username
        - name: ME_CONFIG_BASICAUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-express-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              # reference to configmap name
              name: mongodb-config-map
              key: database_url
        - name: ME_CONFIG_MONGODB_PORT
          valueFrom:
            configMapKeyRef:
              name: mongodb-config-map
              key: database_port
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
    # link to mongo deployment selector above
    app: mongo-express
  type: LoadBalancer
  ports:
    - protocol: TCP
      # service port
      port: 8088
      # containerPort of deployment
      targetPort: 8081
      # from 30000 -> 32767
      nodePort: 30012